---
output:
  pdf_document: default
  html_document: default
---
```{r}
RChunk <- data.frame(Respondents = 1:20, 
                     Sex = c(2,2,1,2,2,2,2,2,2,2,1,2,2,2,2,2,2,2,1,2),
                     Fathers_Occupation = c(1,3,3,3,1,2,3,1,1,1,3,2,1,3,3,1,3,1,2,1),
                     Persons_at_Home = c(5,7,3,8,5,9,6,7,8,4,7,5,4,7,8,8,3,11,7,6),
                     Siblings_at_School = c(6,4,4,1,2,1,5,3,1,2,3,2,5,5,2,1,2,5,3,2),
                     Types_of_Houses = c(1,2,3,1,1,3,3,1,2,3,2,3,2,2,3,3,3,3,3,2))
RChunk
```

```{r}
str(RChunk)
mean(RChunk[,5])
```


```{r}
summary(RChunk)
```

```{r}
RChunk[1:2, 1:6]
```

```{r}
RChunk[3:5, 2:4]
```

```{r}
types_houses <- RChunk[,6]
types_houses
```

```{r}
MaFa <- subset(RChunk, Sex == 1 & Fathers_Occupation == 1, select = c("Sex", "Fathers_Occupation"))
MaFa
```

```{r}
FeSi <- subset(RChunk, Sex==2 & Siblings_at_School>=5, select = c("Sex", "Siblings_at_School"))
FeSi
```

#2.
```{r}
df = data.frame(Ints=integer(),
Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)
print("Structure of the empty dataframe:")
print(str(df))

```

```{r}
path <- "/Users/victo/OneDrive/Desktop/R/RWorksheet3/HouseholdData.csv"
HouseholdData <- read.csv(path)
HouseholdData
```

```{r}
factor(HouseholdData[,2], levels = c("Male", "Female"), labels = c(1,2))
```

```{r}
factor(HouseholdData[,6], levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1,2,3))
```

```{r}
factor(HouseholdData[,3], levels = c(1,2,3), labels = c("Farmer", "Driver", "Others"))
```

```{r}
subset(HouseholdData[c(2,3)], HouseholdData[,2] == 2 & HouseholdData[,3] == "Driver")
```

```{r}
subset(HouseholdData, HouseholdData[,5] >= 5)
```

#4.Interpret the Graph
#The image shows a bar chart with the sentiments of tweets per day. The chart shows the number of negative, neutral, and positive tweets each day from July 14th to July 21st. The chart shows that there were more negative tweets than positive or neutral tweets on most days.