---
output:
  pdf_document: default
  html_document: default
---
#1.
```{r}
Shoesize <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5, 13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 8.5, 10.5, 11.0, 9.0, 13.0)
Height <- c(66.0, 68.0, 64.0, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.0, 67.0, 71.0, 71.0, 77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 69.0, 72.0, 70.0, 69.0, 70.0)
Gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M", "M", "M", "F", "F", "M", "F", "F", "M", "M", "F", "M", "M", "M", "M")
```

```{r}
HouseholdData <- data.frame(Shoesize, Height, Gender)
HouseholdData

write.csv(HouseholdData, "HouseholdData", row.names = FALSE)
```
```{r}
SSMale <- subset(HouseholdData, Gender=="M")
SSMale
SSFemale <- subset(HouseholdData, Gender=="F")
SSFemale
```

```{r}
mean(Shoesize)
mean(Height)
```

#2.
```{r}
months <- c("March","April","January","November","January",
"September","October","September","November","August",
"January","November","November","February","May","August", "July","December","August","August","September","November","February", "April")
```

```{r}
factor_months <- factor(months)
factor_months
```

#3.
```{r}
summary(months)
summary(factor_months)
```

#4.
```{r}
Direction <- c("East", "West", "North")
Frequency <- c(1,4,3)
```

```{r}
DF <- data.frame(Direction, Frequency)
DF
```

```{r}
new_order_data <- factor(Direction,levels = c("East","West","North"))
print(new_order_data)
```

```{r}
ExcelData <- read.table("import_march.csv", header = TRUE, sep = ",", stringsAsFactors = FALSE)
ExcelData
```

```{r}
x <- is.na(as.numeric(readline(prompt = "Select a number from 1 to 50: ")))

if(x >= 50 || x <= 1){
  cat("The number selected is beyond the range of the of 1 to 50")
}else{
  if(x == 20 ){
    cat("TRUE\n")
  }else{
    x
  }
}
```

#7.
```{r}
#wont knit if snackP is interactive T-T
if (interactive()){
snackP <- is.na(as.numeric(readline(prompt= "Input snack price:")))
}else{
  snackP <- 1850
}


if(snackP %% 50 != 0){
  cat("The price must be divisible by 50.\n")
  stop()
}

count <- 0

while(snackP > 0){
  if(snackP >= 1000){
  count <- count + (snackP %/% 1000)
  snackP <- snackP %% 1000
}else if(snackP >= 500){
  count <- count + (snackP %/% 500)
  snackP <- snackP %% 500
}else if(snackP >= 200){
  count <- count + (snackP %/% 200)
  snackP <- snackP %% 200
}else if(snackP >= 100){
  count <- count + (snackP %/% 100)
  snackP <- snackP %% 100
}else if(snackP >= 50){
  count <- count + (snackP %/% 50)
  snackP <- snackP %% 50
 }
}
cat("Minimum number of bills needed:", count, "\n")
```

#8.
#a.
```{r}
Grade_df <- data.frame(Name = c("Annie", "Thea", "Steve", "Hanna"),
                       Grade1 = c(85,65,75,95),
                       Grade2 = c(65,75,55,75),
                       Grade3 = c(85,90,80,100),
                       Grade4 = c(100,90,85,90))
Grade_df
```

#b.
```{r}
Average <- numeric(nrow(Grade_df))

for (i in 1:nrow(Grade_df)){
  TotalG <- Grade_df$Grade1[i] + Grade_df$Grade2[i] + Grade_df$Grade3[i] + Grade_df$Grade4[i]
  Average[i] <- TotalG / 4
}

Grade_df$Average <- Average

studentN <- readline(prompt = "Enter Student Name: ")

if (studentN %in% Grade_df$Name){
  SIndex <- which(Grade_df$Name == studentN)
cat(paste(studentN, "'s average this semester is", round(Grade_df$Average[SIndex], 2), ".\n"))
}else{
  cat("Student's name is not on the records")
}
```
#c.
```{r}
testNum <- ncol(Grade_df) - 1

for (GIndex in 1:testNum) {
  Total <- sum(Grade_df[,GIndex + 1])
  AverageG <- Total / 4
  if(AverageG < 80 ){
    cat(paste("The", GIndex, "test was difficult.\n"))
  }
}
```
#d.
```{r}
studentN <- readline(prompt = "Enter Student Name: ")

if(studentN %in% Grade_df$Name){
  studentR <- Grade_df[Grade_df$Name == studentN, ]
  studentG <- c(studentR$Grade1, studentR$Grade2,
                studentR$Grade3, studentR$Grade4)
  
  HighestG <- 0 
  
  for (grade in studentG){
    if(grade > HighestG){
      HighestG <- grade
    }
  }
  cat(studentN, "'s highest grade is:", HighestG, "\n")
}else{
  cat("Student", studentN, "was not in records")
}

```

